### ISSUE TITLE
Support for screen modes other than 80x25

### ISSUE THREAD

**Issue by FeralChild64** [MattStypa/DOS-Director#4]
Both _DOSBox Staging_ and _DOSBox-X_ provide `MODE` command, which allows to change screen resolution. But it seems _DOS Director_ only supports 80x25 properly:
- when trying to use mode like 132x28, the application just switches to 80x25
- when trying to use mode like 80x50m the application only utilizes the first 25 lines of the display

**Comment by MattStypa** [comment]
@FeralChild64 I looked into this quite a bit and here is what my understanding is.

- I can't detect what Screen mode DOS is currently on. I can request specific screen mode.
- I can't support text modes that are 132 characters wide at this time. It might require a significant architectural change.
- Not supporting 132 wide screen modes is not that big of an issue as I can support 80x60. The additional vertical space can be nice.
- I should be able to support 80x25, 80x30, 80x43, 80x50, 80x60

I think that the best way to do it is via a command line parameter like this:

```
DIRECTOR.EXE MENU.CFG 25 / Default
DIRECTOR.EXE MENU.CFG 30
DIRECTOR.EXE MENU.CFG 43
DIRECTOR.EXE MENU.CFG 50
DIRECTOR.EXE MENU.CFG 60
```

Im going to work on this for version 1.2

**Comment by FeralChild64** [comment]
Can't you just re-use the existing mode? Interrupt `0x10`, function `AH = 0x03` returns the number of columns (`DL`) and rows (`DH`).

**Comment by MattStypa** [comment]
It looks like that interrupt reports cursor position and not the dimensions on the screen but I found a good list of all DOS interrupts and I will check if there is something in there that I can use.

**Comment by MattStypa** [comment]
After doing a lot of research into available interrupts, I think it may be possible.

I am going to give it a try. I'd never thought that I would be writing a responsive app for DOS in 2024. 🤣

**Comment by MattStypa** [comment]
After getting really far with this I ended up scrapping the idea in this version of DOS Director.

I have a vision for DOS Director 2 that is graphics based.
